version: '3'

services:
  app:
    build: modelcls
    entrypoint: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports: 
      - "8000:8000"
    restart: always

  queues:
    env_file:
      - .env
    build: modelcls
    entrypoint: [ "python", "queues.py"]
    restart: always
    networks:
      - site_rabbitmq


  platform_queues:
    volumes:
      - ./:/src/
    env_file:
      - .env
    build: platform
    entrypoint: [ "python", "queues.py"]
    restart: always
    networks:
      - site_rabbitmq


  # db:
  #   image: nouchka/sqlite3:latest
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./:/root/db/
  #   stdin_open: true
  #   tty: true
  #   restart: always


# TODO: configure networks


networks:
  site_rabbitmq:
    external: true