version: '3.5'

services:
  app:
    build: modelcls
    entrypoint: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports: 
      - "8000:8000"
    restart: always

  queues:
    env_file:
      - .env
    build: modelcls
    entrypoint: [ "python", "queues.py"]
    restart: always
    networks:
      - site_rabbitmq


  platform_queues:
    volumes:
      - ./:/src/
    env_file:
      - .env
    build: platform
    entrypoint: [ "python", "queues.py"]
    restart: always
    networks:
      - site_rabbitmq

  

networks:
  site_rabbitmq:
    external: true